### ISSUE TITLE
 Nitrous not working

### ISSUE THREAD

**Issue by word4wisdom** [learn-co-curriculum/looping-for#16]
My Nitrous session was terminated while doing a lab and I keep getting this error message every time I try to initiate a new session-was working fine prior to this point. Any suggestions?

Error Message: "whoops! There was a problem opening this lab.
                           Failed to login vis SSH. Have you added learn.co's public-
                           key to your Nitrous container?"

**Comment by AnnJohn** [comment]
hi @word4wisdom sorry for the trouble you're having. since this might be an issue specific to you, please use the Ask a Question tool in Learn and someone from our support team will get back to you right away. Thanks!
