### ISSUE TITLE
example suggestion

### ISSUE THREAD

**Issue by aenbar** [learn-co-curriculum/looping-for#2]
I see a lot of examples in our labs that are self-contained. ie. in this one - 

"Imagine we have a collection or a list of objects. Let's say your are a prominent collector of sneakers and you are going through your sneaker collection and preforming a certain action, putting them away in their box, for each pair. If you have 32 paris of sneakers, you need to preform that action 32 times, once for each pair. We could do this with one of the constructors we've learned so far"

One of the things that I hear people complain a lot about other learning platforms is that it's hard to see how what you're doing actually connects to the bigger picture. Given that, it may be valuable to start using examples that are more "realistic."

For example, rather than saying you want to put 32 sneakers in a box, maybe we can give a more realistic example. Like "if you were building a stopwatch" or better yet "if you were building a social network called bookface and wanted to let a user do XYZ..."

I'm sure that's easier said than done, but the more the examples can be connected to real-world programming tasks the more I think people will connect with them.

**Comment by AnnJohn** [comment]
Closing issue
