### ISSUE TITLE
For check in checklist

### ISSUE THREAD

**Issue by NoneOfMaster** [learn-co-curriculum/looping-for#8]
I was able to make this work by using: 
for check in check_list
But that was pretty much a blind guess based on the shoe_count example given, which I don't fully understand. I'm wondering if there is an explanation or even a name for the "check" element in the code which I essentially just made up to have something in between "for" and "in" - what is that thing?

**Comment by AnnJohn** [comment]
@SophieDeBenedetto due 8/21
